# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# Minimal analysis options: the original include referenced package:flutter_lints
# which is not available in some analysis environments for this workspace.
# To avoid a noisy include_file_not_found warning, provide a minimal
# configuration here and enable rules selectively.

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/gen/**"

linter:
  rules:
    # Enable or disable project lints here. Keep minimal to avoid false positives.
    avoid_print: false

# If you want the full set of flutter recommended lints, restore the include
# after ensuring the package is resolvable in your environment:
# include: package:flutter_lints/flutter.yaml
