name: flutter_desktop_app
description: DPR Assessment System for MDoNER (Desktop)
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.0
  flutter_svg: ^2.0.4
  # upgraded to a modern version compatible with v2 Android embedding
  file_picker: ^10.3.3
  # updated to a newer version with Android namespace support
  desktop_drop: ^0.6.1
  shared_preferences: ^2.0.15
  path_provider: ^2.0.9
  back_button_interceptor: ^6.0.0
  http: ^0.13.6
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: any

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
